<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-I05LRQH" failures="0" tests="4" name="com.testng.Dependency_Concepts" time="0.022" errors="1" timestamp="2022-12-27T12:14:05 IST" skipped="0">
  <testcase classname="com.testng.Dependency_Concepts" name="logout" time="0.005"/>
  <system-out/>
  <testcase classname="com.testng.Dependency_Concepts" name="browser" time="0.001">
    <error message="
Method Dependency_Concepts.browser()[pri:0, instance:com.testng.Dependency_Concepts@53976f5c] should have thrown an exception of type class org.testng.TestException" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method Dependency_Concepts.browser()[pri:0, instance:com.testng.Dependency_Concepts@53976f5c] should have thrown an exception of type class org.testng.TestException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- browser -->
  <system-out/>
  <testcase classname="com.testng.Dependency_Concepts" name="credentials" time="0.015"/>
  <system-out/>
  <testcase classname="com.testng.Dependency_Concepts" name="login" time="0.001"/>
  <system-out/>
</testsuite> <!-- com.testng.Dependency_Concepts -->
